### ISSUE TITLE
INFOGRAFIA_LUZ KARINA

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-1-infografia-ka194#2]
[infografia_luz karina.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-ka194/files/12489413/infografia_luz.karina.pdf)

**Comment by Alvaro2-0** [comment]
Buen trabajo 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
